[cph-gpu5.uncc.edu:33466] mca_base_component_repository_open: unable to open mca_oob_ud: libosmcomp.so.3: cannot open shared object file: No such file or directory (ignored)
[cph-gpu5.uncc.edu:33451] mca_base_component_repository_open: unable to open mca_oob_ud: libosmcomp.so.3: cannot open shared object file: No such file or directory (ignored)
[cph-gpu5.uncc.edu:33451] mca_base_component_repository_open: unable to open mca_btl_openib: libosmcomp.so.3: cannot open shared object file: No such file or directory (ignored)
[cph-gpu5.uncc.edu:33451] mca_base_component_repository_open: unable to open mca_pml_ucx: libucp.so.0: cannot open shared object file: No such file or directory (ignored)
2019-07-17 00:33:18.737597: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX512F
2019-07-17 00:33:18.895339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:60:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2019-07-17 00:33:18.895379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2019-07-17 00:33:19.349567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-17 00:33:19.349615: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2019-07-17 00:33:19.349624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2019-07-17 00:33:19.349760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:60:00.0, compute capability: 6.1)
WARNING:tensorflow:From /apps/pkg/tensorflow-1.7.0/rhel7_u2-x86_64_ana3/cuda9/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "/users/hdhawale/gitfolder/MachineLearning-Research/generalization/atari/BaseDQN_atari/train.py", line 153, in <module>
    main()
  File "/users/hdhawale/gitfolder/MachineLearning-Research/generalization/atari/BaseDQN_atari/train.py", line 138, in main
    with open(resultPath + str(it) +'_weights.pk1', 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/users/hdhawale/gitfolder/MachineLearning-Research/generalization/atari/BaseDQN_atari/results/Pong/pong_results/0_weights.pk1'
